apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: i-kokyaku2
  name: i-kokyaku2
  namespace: bgd
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: i-kokyaku2
    weight: 100
