---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: i-kokyaku2
  name: i-kokyaku2
  namespace: bgd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-kokyaku2
---
