---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kokyaku
  name: kokyaku
  namespace: bgd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kokyaku
---
