apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: c
  namespace: openshift-gitops
spec:
  description:  C project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
