apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kokyaku-app
  namespace: openshift-gitops
spec: 
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: b
  source: 
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
