apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - app: bgd
          - app: bgd2
  template:
    metadata:
      name: 'd-{{app}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: overlays/develop/genkohoshu-01/d/{{app}}
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        targetRevision: HEAD
