apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd
  namespace: openshift-gitops
spec:
  syncPolicy:
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        directories:
          - path: overlays/develop/genkohoshu-01/d/*
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        revision: HEAD
  template:
    metadata:
      name: 'd-{{.path.basenameNormalized}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{.path.path}}'
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        targetRevision: HEAD
      syncPolicy:
        automated: []