apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: genkohoshu-01
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        directories:
          - path: overlays/develop/genkohoshu-01/*/*
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        revision: HEAD
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-{{index .path.segments 2}}'
      labels:
        dest.space: '{{index .path.segments 2}}'
        app.continername: '{{.path.basenameNormalized}}'
        app.subsystem: '{{index .path.segments 3}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: '{{index .path.segments 3}}'
      source:
        path: '{{.path.path}}'
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        targetRevision: HEAD
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSyncOnly=true