---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: kokyaku
  namespace: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kokyaku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kokyaku
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
