apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - app: bgd
          - app: bgd2
  template:
    metadata:
      name: '{test-{app}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: btest
      source:
        path: apps/bgd/overlays/bgd
        repoURL: https://github.com/IbukiMnw/openshift-gitops-examples
        targetRevision: main
