apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  generators:
    - git:
        directories:
          - path: apps/bgd/overlays/*/
        repoURL: 'https://github.com/redhat-developer-demos/openshift-gitops-examples'
        revision: main
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{test-{.path.basenameNormalized}}'
    spec:
      destination:
        server: 'https://kubernetes.default.svc'
      project: btest
      source:
        path: '{{.path.path}}' 
        repoURL: 'https://github.com/IbukiMnw/openshift-gitops-examples'
        targetRevision: main
      syncPolicy:
        automated: {}