---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: i-kokyaku1
  name: i-kokyaku1
  namespace: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i-kokyaku1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: i-kokyaku1
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: i-kokyaku1
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
